#!/bin/bash
# Version 5

### Clear SVG cache
rm ~/.cache/plasma-svgelements-*

killall plasmawindowed
QML_DISABLE_DISK_CACHE=true plasmawindowed --applet org.kde.plasma.volumewin7mixer

### 2x DPI Test
# QT_DEVICE_PIXEL_RATIO=2 QML_DISABLE_DISK_CACHE=true plasmawindowed --applet org.kde.plasma.volumewin7mixer

### Test French Locale
# LANG=fr_FR.UTF-8 QML_DISABLE_DISK_CACHE=true plasmawindowed --applet org.kde.plasma.volumewin7mixer
